from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS payments (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id integer NOT NULL UNIQUE,
                        amount numeric(12, 2) NOT NULL,
                        status varchar(20) NOT NULL,
                        payment_method varchar(50) NOT NULL,
                        event_id varchar(128) NOT NULL UNIQUE,
                        processed_at timestamp with time zone NOT NULL DEFAULT now()
                    );
                    CREATE TABLE IF NOT EXISTS processed_events (
                        event_id varchar(128) PRIMARY KEY,
                        created_at timestamp with time zone NOT NULL DEFAULT now()
                    );
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Payment',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('order_id', models.IntegerField(unique=True)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('status', models.CharField(max_length=20)),
                        ('payment_method', models.CharField(max_length=50)),
                        ('event_id', models.CharField(max_length=128, unique=True)),
                        ('processed_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'payments',
                    },
                ),
                migrations.CreateModel(
                    name='ProcessedEvent',
                    fields=[
                        ('event_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'processed_events',
                    },
                ),
            ],
        ),
    ]
