from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS stock (
                        product_id integer PRIMARY KEY,
                        available integer NOT NULL,
                        reserved integer NOT NULL DEFAULT 0
                    );
                    CREATE TABLE IF NOT EXISTS stock_reservations (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id integer NOT NULL UNIQUE,
                        product_id integer NOT NULL,
                        quantity integer NOT NULL,
                        reserved_at timestamp with time zone NOT NULL DEFAULT now()
                    );
                    CREATE TABLE IF NOT EXISTS processed_events (
                        event_id varchar(128) PRIMARY KEY,
                        created_at timestamp with time zone NOT NULL DEFAULT now()
                    );
                    INSERT INTO stock (product_id, available, reserved) VALUES
                        (101, 10, 0),
                        (102, 5, 0),
                        (103, 3, 0)
                    ON CONFLICT (product_id) DO NOTHING;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Stock',
                    fields=[
                        ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                        ('available', models.IntegerField()),
                        ('reserved', models.IntegerField()),
                    ],
                    options={
                        'db_table': 'stock',
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='Reservation',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('order_id', models.IntegerField(unique=True)),
                        ('product_id', models.IntegerField()),
                        ('quantity', models.IntegerField()),
                        ('reserved_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'stock_reservations',
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='ProcessedEvent',
                    fields=[
                        ('event_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'processed_events',
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
