from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS shipments (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id integer NOT NULL UNIQUE,
                        shipment_id varchar(100) NOT NULL UNIQUE,
                        product_id integer NOT NULL,
                        quantity integer NOT NULL,
                        status varchar(50) NOT NULL,
                        shipped_at timestamp with time zone NOT NULL DEFAULT now()
                    );
                    CREATE TABLE IF NOT EXISTS pending_payments (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_id integer NOT NULL UNIQUE,
                        amount numeric(12, 2) NOT NULL,
                        status varchar(30) NOT NULL DEFAULT 'WAITING_FOR_STOCK',
                        event_id varchar(128) NOT NULL UNIQUE,
                        created_at timestamp with time zone NOT NULL DEFAULT now()
                    );
                    CREATE TABLE IF NOT EXISTS processed_events (
                        event_id varchar(128) PRIMARY KEY,
                        created_at timestamp with time zone NOT NULL DEFAULT now()
                    );
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Reservation',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('order_id', models.IntegerField(unique=True)),
                        ('product_id', models.IntegerField()),
                        ('quantity', models.IntegerField()),
                    ],
                    options={
                        'db_table': 'stock_reservations',
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='Shipment',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('order_id', models.IntegerField(unique=True)),
                        ('shipment_id', models.CharField(max_length=100, unique=True)),
                        ('product_id', models.IntegerField()),
                        ('quantity', models.IntegerField()),
                        ('status', models.CharField(max_length=50)),
                        ('shipped_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'shipments',
                    },
                ),
                migrations.CreateModel(
                    name='PendingPayment',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('order_id', models.IntegerField(unique=True)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('status', models.CharField(default='WAITING_FOR_STOCK', max_length=30)),
                        ('event_id', models.CharField(max_length=128, unique=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'pending_payments',
                    },
                ),
                migrations.CreateModel(
                    name='ProcessedEvent',
                    fields=[
                        ('event_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'processed_events',
                    },
                ),
            ],
        ),
    ]
