from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS stock_reservations (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id integer NOT NULL UNIQUE,
                product_id integer NOT NULL,
                quantity integer NOT NULL,
                reserved_at timestamp with time zone NOT NULL DEFAULT now()
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
